# Generated by Django 4.2.7 on 2023-11-18 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activate_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Activate code'),
        ),
    ]
