# Generated by Django 4.2.7 on 2023-11-12 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trendyol', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
