# Generated by Django 4.2.7 on 2023-11-12 22:43

from django.conf import settings
from django.db import migrations, models
import services.uploader


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trendyol', '0003_category_created_at_category_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Shop name')),
                ('logo', models.ImageField(upload_to=services.uploader.Uploader.upload_photo_for_shop, verbose_name='Shop logo')),
                ('status', models.CharField(max_length=255, verbose_name="Shop's main feature")),
                ('location', models.CharField(max_length=255, verbose_name='Location of shop')),
                ('trendyol_adventure_time', models.CharField(max_length=255, verbose_name='Time length in Trendyol')),
                ('have_receipt', models.BooleanField(default=True)),
                ('answer_time', models.CharField(max_length=255, verbose_name='Average reply time')),
                ('cargo_time', models.CharField(max_length=255, verbose_name='Average to cargo time')),
                ('rating', models.FloatField(editable=False, verbose_name='Rating value')),
                ('followers', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Followers of shop')),
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Shops',
                'ordering': ('rating', '-created_at'),
            },
        ),
    ]
