# Generated by Django 4.2.7 on 2023-11-12 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trendyol', '0005_colors_sizes_tags_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colors',
            name='photo',
        ),
    ]
