# Generated by Django 4.2.7 on 2023-11-12 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendyol', '0006_remove_colors_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='rating',
            field=models.FloatField(default=0, editable=False, verbose_name='Rating value'),
        ),
    ]
