# Generated by Django 4.2.7 on 2023-11-12 23:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trendyol', '0007_alter_shop_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='Followers of shop'),
        ),
    ]
