# Generated by Django 4.2.7 on 2023-11-12 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendyol', '0008_alter_shop_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=0, editable=False, verbose_name='Rating of product'),
        ),
    ]
