# Generated by Django 4.2.7 on 2023-11-14 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trendyol', '0014_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='slug',
        ),
    ]
